module.exports = {
   DATABASE_NAME: process.env.DATABASE_NAME,
   SECRET_ARN: process.env.SECRET_ARN,
   DATABASE_ARN: process.env.DATABASE_ARN,
   DATABASE_REGION: process.env.DATABASE_REGION,
   DATABASE_USERNAME: process.env.DATABASE_USERNAME,
   DATABASE_PASSWORD: process.env.DATABASE_PASSWORD,
   DATABASE_HOST: process.env.DATABASE_HOST
}
